export const routes = {
    cards: '/cards',
    profile: '/profile',
    login: '/login',
    registration: '/registration',
    forgotPassword: '/forgotPassword',
    newPassword: '/newPassword',
    passwordRecovery: '/passwordRecovery',
    test: '/test',
    error404: '/404',
    friendsPacksList: '/packs/friends-packs/:urlPackId',
    packsList: '/packs/',
    myPacksList: '/packs/my-packs/:urlPackId',
    pagePack: '/packs/pack/',
    learnPack: '/packs/learn/:urlPackId',
    withoutCards: '/no-cards/:urlPackId',
}
