export const routes = {
    cards: '/cards',
    profile: '/profile',
    login: '/login',
    registration: '/registration',
    forgotPassword: '/forgotPassword',
    newPassword: '/newPassword',
    passwordRecovery: '/passwordRecovery',
    test: '/test',
    error404: '/404',
    packsList: '/cards/pack-list',
    friendsPacksList: '/cards/friend-list',
    myPacksList: '/cards/my-list',
    pagePack: '/cards/page-pack',
}
